version: '3.1'
services:
  app:
    build: 
      context: /
      dockerfile: /dockerfile
    restart: always
    depends_on: 
      db:
        condition: service_healthy
    ports:
      - "5656:5656"
  
  db:
    image: mysql
    container_name: my_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "1111"
      MYSQL_DATABASE: "db"
      MYSQL_USER: "ROOT"
      MYSQL_PASSWORD: "1111"
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 20
  
volumes:
  db_data: 